name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login Dockerhub
      env:
       DOCKER_USERNAME: ${{secret.DOCKER_USERNAME}}
       DOCKER_PASSWORD: ${{secret.DOCKER_PASSWORD}}
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t cicd-pipeline .
    - name: push to Dockerhub
      run: docker push noxxspring/cicd-pipeline:latest
