version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Expose FastAPI app to port 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount custom nginx.conf
    ports:
      - "80:80"  # Expose Nginx to port 80
    depends_on:
      - fastapi

