name: CI Pipeline - Test

on:
  pull_request:
    branches:
      - main  # Trigger the workflow when there's a PR to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code in the PR

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests with pytest
      run: |
        pytest  # Run the tests with pytest

    - name: Upload test results (optional)
      if: failure()
      run: |
        echo "Test failed!"
